# Generated by Django 4.2.9 on 2024-08-01 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_order_options_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date_peremption',
            field=models.DateField(default='2024-08-01'),
        ),
        migrations.AddField(
            model_name='product',
            name='seuil_maximum',
            field=models.IntegerField(default=-100),
        ),
        migrations.AddField(
            model_name='product',
            name='seuil_minimum',
            field=models.IntegerField(default=100),
        ),
    ]
