# Generated by Django 4.2.9 on 2024-08-01 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_product_date_peremption_product_seuil_maximum_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='seuil_maximum',
        ),
        migrations.RemoveField(
            model_name='product',
            name='seuil_minimum',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='avatar.jpg', upload_to='profile_images'),
        ),
    ]
