# Generated by Django 4.2.9 on 2024-08-02 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_client_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='adresse',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
