# Generated by Django 4.2.9 on 2024-08-02 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_alter_client_adresse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('adresse', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Fournisseur',
            },
        ),
    ]
