# Generated by Django 4.2.9 on 2024-08-03 00:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_product_fournisseur'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='designation',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='prix',
            field=models.DecimalField(decimal_places=2, default=3, max_digits=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='date_peremption',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
