# Generated by Django 4.2.9 on 2024-08-05 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_remove_order_date_remove_order_staff_order_client_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='quantity',
            new_name='quantite',
        ),
    ]
