# Generated by Django 4.2.9 on 2024-08-05 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_rename_quantity_order_quantite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quantity',
            new_name='quantite',
        ),
    ]
